
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADDRESS ALLOW ASSIGN CLIENTS CLOSE COLON COMMA CONNECT CONNECTION FLOAT IN INFO INITIATE INT IP KEYWORD MESSAGE NAME PORT SEND SERVER SHOW STRING TO\n    run_command : create_server\n                | allow_conns\n                | close_connection\n                | show_clients\n                | close_client_connection_in_server\n                | create_client\n                | send_message\n                | send_spec_message\n                | create_server_for_all\n                | show_server_info\n    \n    create_server : INITIATE SERVER COLON ADDRESS IP COMMA PORT INT COMMA NAME STRING\n    \n    create_server_for_all : INITIATE SERVER COLON PORT INT COMMA NAME STRING\n    \n    create_client : CONNECT TO SERVER COLON ADDRESS IP COMMA PORT INT\n    \n    allow_conns : ALLOW CONNECTION IN STRING COLON INT\n    \n    show_clients : SHOW CLIENTS INFO IN STRING\n    \n    show_server_info : SHOW STRING INFO\n    \n    close_connection : CLOSE CONNECTION COLON STRING\n    \n    close_client_connection_in_server : CLOSE CONNECTION COLON STRING IN STRING\n    \n    send_message : SEND MESSAGE COLON STRING\n    \n    send_spec_message : SEND MESSAGE TO STRING COLON STRING\n    '
    
_lr_action_items = {'INITIATE':([0,],[12,]),'ALLOW':([0,],[13,]),'CLOSE':([0,],[14,]),'SHOW':([0,],[15,]),'CONNECT':([0,],[16,]),'SEND':([0,],[17,]),'$end':([1,2,3,4,5,6,7,8,9,10,11,29,36,39,45,50,51,53,58,61,63,],[0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10,-16,-17,-19,-15,-14,-18,-20,-12,-13,-11,]),'SERVER':([12,23,],[18,30,]),'CONNECTION':([13,14,],[19,20,]),'CLIENTS':([15,],[21,]),'STRING':([15,26,27,31,32,37,44,47,55,62,],[22,35,36,39,40,45,51,53,58,63,]),'TO':([16,24,],[23,32,]),'MESSAGE':([17,],[24,]),'COLON':([18,20,24,30,35,40,],[25,27,31,38,43,47,]),'IN':([19,28,36,],[26,37,44,]),'INFO':([21,22,],[28,29,]),'ADDRESS':([25,38,],[33,46,]),'PORT':([25,48,56,],[34,54,59,]),'IP':([33,46,],[41,52,]),'INT':([34,43,54,59,],[42,50,57,61,]),'COMMA':([41,42,52,57,],[48,49,56,60,]),'NAME':([49,60,],[55,62,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'run_command':([0,],[1,]),'create_server':([0,],[2,]),'allow_conns':([0,],[3,]),'close_connection':([0,],[4,]),'show_clients':([0,],[5,]),'close_client_connection_in_server':([0,],[6,]),'create_client':([0,],[7,]),'send_message':([0,],[8,]),'send_spec_message':([0,],[9,]),'create_server_for_all':([0,],[10,]),'show_server_info':([0,],[11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> run_command","S'",1,None,None,None),
  ('run_command -> create_server','run_command',1,'p_run_command','pyCon_parser.py',28),
  ('run_command -> allow_conns','run_command',1,'p_run_command','pyCon_parser.py',29),
  ('run_command -> close_connection','run_command',1,'p_run_command','pyCon_parser.py',30),
  ('run_command -> show_clients','run_command',1,'p_run_command','pyCon_parser.py',31),
  ('run_command -> close_client_connection_in_server','run_command',1,'p_run_command','pyCon_parser.py',32),
  ('run_command -> create_client','run_command',1,'p_run_command','pyCon_parser.py',33),
  ('run_command -> send_message','run_command',1,'p_run_command','pyCon_parser.py',34),
  ('run_command -> send_spec_message','run_command',1,'p_run_command','pyCon_parser.py',35),
  ('run_command -> create_server_for_all','run_command',1,'p_run_command','pyCon_parser.py',36),
  ('run_command -> show_server_info','run_command',1,'p_run_command','pyCon_parser.py',37),
  ('create_server -> INITIATE SERVER COLON ADDRESS IP COMMA PORT INT COMMA NAME STRING','create_server',11,'p_create_server','pyCon_parser.py',45),
  ('create_server_for_all -> INITIATE SERVER COLON PORT INT COMMA NAME STRING','create_server_for_all',8,'p_create_server_for_all','pyCon_parser.py',54),
  ('create_client -> CONNECT TO SERVER COLON ADDRESS IP COMMA PORT INT','create_client',9,'p_create_client','pyCon_parser.py',63),
  ('allow_conns -> ALLOW CONNECTION IN STRING COLON INT','allow_conns',6,'p_allow_conns','pyCon_parser.py',77),
  ('show_clients -> SHOW CLIENTS INFO IN STRING','show_clients',5,'p_show_clients','pyCon_parser.py',88),
  ('show_server_info -> SHOW STRING INFO','show_server_info',3,'p_show_server_info','pyCon_parser.py',98),
  ('close_connection -> CLOSE CONNECTION COLON STRING','close_connection',4,'p_close_connection','pyCon_parser.py',108),
  ('close_client_connection_in_server -> CLOSE CONNECTION COLON STRING IN STRING','close_client_connection_in_server',6,'p_close_client_connection_in_server','pyCon_parser.py',122),
  ('send_message -> SEND MESSAGE COLON STRING','send_message',4,'p_send_message','pyCon_parser.py',134),
  ('send_spec_message -> SEND MESSAGE TO STRING COLON STRING','send_spec_message',6,'p_send_spec_message','pyCon_parser.py',146),
]
