
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADDRESS ALLOW ASSIGN CLIENTS CLOSE COLON COMMA CONNECT CONNECTION FLOAT IN INFO INITIATE INT IP KEYWORD MESSAGE NAME PORT SEND SERVER SHOW STRING TO\n    run_command : create_server\n                | allow_conns\n                | close_connection\n                | show_clients\n                | close_client_connection_in_server\n                | create_client\n                | send_message\n                | send_spec_message\n                | create_server_for_all\n    \n    create_server : INITIATE SERVER COLON ADDRESS IP COMMA PORT INT COMMA NAME STRING\n    \n    create_server_for_all : INITIATE SERVER COLON PORT INT COMMA NAME STRING\n    \n    create_client : CONNECT TO SERVER COLON ADDRESS IP COMMA PORT INT\n    \n    allow_conns : ALLOW CONNECTION IN STRING COLON INT\n    \n    show_clients : SHOW CLIENTS INFO IN STRING\n    \n    close_connection : CLOSE CONNECTION COLON STRING\n    \n    close_client_connection_in_server : CLOSE CONNECTION COLON STRING IN STRING\n    \n    send_message : SEND MESSAGE COLON STRING\n    \n    send_spec_message : SEND MESSAGE TO STRING COLON STRING\n    '
    
_lr_action_items = {'INITIATE':([0,],[11,]),'ALLOW':([0,],[12,]),'CLOSE':([0,],[13,]),'SHOW':([0,],[14,]),'CONNECT':([0,],[15,]),'SEND':([0,],[16,]),'$end':([1,2,3,4,5,6,7,8,9,10,33,36,42,47,48,50,55,58,60,],[0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-15,-17,-14,-13,-16,-18,-11,-12,-10,]),'SERVER':([11,21,],[17,27,]),'CONNECTION':([12,13,],[18,19,]),'CLIENTS':([14,],[20,]),'TO':([15,22,],[21,29,]),'MESSAGE':([16,],[22,]),'COLON':([17,19,22,27,32,37,],[23,25,28,35,40,44,]),'IN':([18,26,33,],[24,34,41,]),'INFO':([20,],[26,]),'ADDRESS':([23,35,],[30,43,]),'PORT':([23,45,53,],[31,51,56,]),'STRING':([24,25,28,29,34,41,44,52,59,],[32,33,36,37,42,48,50,55,60,]),'IP':([30,43,],[38,49,]),'INT':([31,40,51,56,],[39,47,54,58,]),'COMMA':([38,39,49,54,],[45,46,53,57,]),'NAME':([46,57,],[52,59,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'run_command':([0,],[1,]),'create_server':([0,],[2,]),'allow_conns':([0,],[3,]),'close_connection':([0,],[4,]),'show_clients':([0,],[5,]),'close_client_connection_in_server':([0,],[6,]),'create_client':([0,],[7,]),'send_message':([0,],[8,]),'send_spec_message':([0,],[9,]),'create_server_for_all':([0,],[10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> run_command","S'",1,None,None,None),
  ('run_command -> create_server','run_command',1,'p_run_command','pyCon_parser.py',28),
  ('run_command -> allow_conns','run_command',1,'p_run_command','pyCon_parser.py',29),
  ('run_command -> close_connection','run_command',1,'p_run_command','pyCon_parser.py',30),
  ('run_command -> show_clients','run_command',1,'p_run_command','pyCon_parser.py',31),
  ('run_command -> close_client_connection_in_server','run_command',1,'p_run_command','pyCon_parser.py',32),
  ('run_command -> create_client','run_command',1,'p_run_command','pyCon_parser.py',33),
  ('run_command -> send_message','run_command',1,'p_run_command','pyCon_parser.py',34),
  ('run_command -> send_spec_message','run_command',1,'p_run_command','pyCon_parser.py',35),
  ('run_command -> create_server_for_all','run_command',1,'p_run_command','pyCon_parser.py',36),
  ('create_server -> INITIATE SERVER COLON ADDRESS IP COMMA PORT INT COMMA NAME STRING','create_server',11,'p_create_server','pyCon_parser.py',44),
  ('create_server_for_all -> INITIATE SERVER COLON PORT INT COMMA NAME STRING','create_server_for_all',8,'p_create_server_for_all','pyCon_parser.py',53),
  ('create_client -> CONNECT TO SERVER COLON ADDRESS IP COMMA PORT INT','create_client',9,'p_create_client','pyCon_parser.py',62),
  ('allow_conns -> ALLOW CONNECTION IN STRING COLON INT','allow_conns',6,'p_allow_conns','pyCon_parser.py',76),
  ('show_clients -> SHOW CLIENTS INFO IN STRING','show_clients',5,'p_show_clients','pyCon_parser.py',87),
  ('close_connection -> CLOSE CONNECTION COLON STRING','close_connection',4,'p_close_connection','pyCon_parser.py',97),
  ('close_client_connection_in_server -> CLOSE CONNECTION COLON STRING IN STRING','close_client_connection_in_server',6,'p_close_client_connection_in_server','pyCon_parser.py',111),
  ('send_message -> SEND MESSAGE COLON STRING','send_message',4,'p_send_message','pyCon_parser.py',124),
  ('send_spec_message -> SEND MESSAGE TO STRING COLON STRING','send_spec_message',6,'p_send_spec_message','pyCon_parser.py',136),
]
